apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: catalog
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
data:
  MYSQL_HOST: mysql
  MYSQL_DATABASE: catalog
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      serviceAccountName: catalog
      containers:
        - name: catalog
          image: ghcr.io/huycon2352/catalog:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-config
            - secretRef:
                name: catalog-db-secret
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: catalog-db-secret
