apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Huycon2352/Devsecops.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true