apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/tehn145/retail-store-sample-app
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
